name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Code Lint
        run: cargo clippy --verbose -- -D warnings
      - name: Format Check
        run: cargo fmt -- --check
